build(deps): integrate external Libft

diff --git a/minitalk/Makefile b/minitalk/Makefile
--- a/minitalk/Makefile
+++ b/minitalk/Makefile
@@ -35,10 +35,11 @@ CLIENT_OBJ_USED = $(CLIENT_SRC_USED:.c=.o)
 SERVER_OBJ_ALL = $(SERVER_SRC:.c=.o) $(SERVER_SRC_BONUS:.c=.o)
 CLIENT_OBJ_ALL = $(CLIENT_SRC:.c=.o) $(CLIENT_SRC_BONUS:.c=.o)
 
-INCLUDE = -Iinclude -Ilibft
-
-LIBFT_DIR = libft
+LIBFT_REPO_DIR = ../external/libft
+LIBFT_DIR = $(LIBFT_REPO_DIR)/libft
 LIBFT = $(LIBFT_DIR)/libft.a
+
+INCLUDE = -Iinclude -I$(LIBFT_DIR)
 
 # **************************************************************************** #
 # ****************************** RULES: ************************************** #
@@ -56,6 +57,11 @@ $(MODE_STAMP): | $(BUILD_STATE_DIR)
 	touch $(MODE_STAMP)
 
 $(LIBFT):
+	@if [ ! -f "$(LIBFT_DIR)/Makefile" ]; then \
+		echo "Error: Libft submodule is not initialized."; \
+		echo "Run: git submodule update --init --recursive"; \
+		exit 1; \
+	fi
 	$(MAKE) -C $(LIBFT_DIR)
 
 $(SERVER_NAME): $(SERVER_OBJ_USED) $(LIBFT) $(MODE_STAMP)
